name: GitHub Action flow to Docker hub 

on:
  push:
    branches: [main]

jobs:
  build-push-images:
    name: Budowa i publikacja obrazu na repozytorium
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      # Akcja: "checkout" - sprawdza, czy workflow ma poprawny dostęp do repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Akcja: "docker/setup-buildx-action" - konfiguruje buildx'a, przez co będzie możliwość budowania obrazów na wiele architektur
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v2

      # Akcja: "docker/setup-qemu-action" - "instalacja" emelatora dla wielu architektur
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Akcja: "docker/login-action" - logowanie na konto Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Akcja: "docker/login-action" - logowanie do registru kontenerow
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Akcja: "build-push-action" - zbudowanie i wypchnięcie obrazów na DockerHub registry
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/lab:fibcalc
            ghcr.io/${{ github.repository_owner }}/lab:fibcalc
          cache-from: type=registry,src=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/lab:fibcalccache
          cache-to: type=registry,dest=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/lab:fibcalccache
          